name: Add Dependency Information to PR

on:
  workflow_run:
    workflows: ["Update Freetz-NG Prerequisites"]
    types:
      - completed

jobs:
  comment_pr:
    env:
      BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ env.BRANCH_NAME }}
    - name: Run scripts/dependency-diff.sh
      run: bash scripts/dependency-diff.sh provisioning >.dependency-diff.txt
    - name: Get PR number
      id: get_pr_number
      env:
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
      run: |
        PR_NUMBER=$(gh pr list --state open --head "$BRANCH_NAME" --json number -q '.[0].number')
        if [ -z "$PR_NUMBER" ]; then
          echo "No open PR found for branch $BRANCH_NAME, exiting."
          exit 0
        fi
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
    - name: Comment PR
      if: ${{ steps.get_pr_number.outputs.PR_NUMBER != '' }}
      uses: thollander/actions-comment-pull-request@v3
      with:
        github-token: ${{ secrets.PR_PAT }}
        pull-request-number: ${{ steps.get_pr_number.outputs.PR_NUMBER }}
        file-path: .dependency-diff.txt
