name: Matrix Docker Build & Push

on:
  schedule:
    - cron: "32 14 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
      VERSION: "0.0.1"
      HTTP_PROXY: ${{ secrets.HTTP_PROXY || '' }}
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY || '' }}
      BUILD_ARGS: |
        PARENT=${{ matrix.base }}
        ${HTTP_PROXY:+http_proxy=${HTTP_PROXY}}
        ${HTTPS_PROXY:+https_proxy=${HTTPS_PROXY}}

    strategy:
      fail-fast: false
      matrix:
        base:
          - debian:11
          - debian:12
          - debian:13
          - debian:14
          - fedora:41
          - fedora:42
          - fedora:43
          - fedora:44
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - ubuntu:26.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate tag name
        id: tag
        shell: bash
        run: |
          IMAGE="${{ matrix.base }}"

          # Split into distro + version
          DISTRO=$(echo "$IMAGE" | cut -d: -f1)
          VER=$(echo "$IMAGE" | cut -d: -f2)
          VERSION="v${{ env.VERSION }}"

          TAG="${DISTRO}-${VER}-${VERSION}"

          echo "Generated tag: $TAG"
          echo "DISTRO=$DISTRO" >> $GITHUB_OUTPUT
          echo "VER=$VER" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO }}
          tags: |
            ${{ steps.tag.outputs.DISTRO }}-${{ steps.tag.outputs.VER }}-${{ steps.tag.outputs.VERSION }}
            ${{ steps.tag.outputs.DISTRO }}-${{ steps.tag.outputs.VER }}-latest

      - name: Build & Push
        id: push
        continue-on-error: true
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with: &build_args
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: ${{ env.BUILD_ARGS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Retry Build & Push
        if: ${{ steps.push.outcome == 'failure' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with: *build_args
