name: Matrix Docker Build & Push

on:
  schedule:
    - cron: "32 14 1 * *"
  workflow_dispatch:

jobs:
  build-prepare:
    runs-on: ubuntu-slim
    env:
      REGISTRY: ghcr.io
      REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
      VERSION: "0.0.1"
      HTTP_PROXY: ${{ secrets.HTTP_PROXY || '' }}
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY || '' }}
    outputs:
      image: ${{ steps.set-outputs.outputs.image }}
      registry: ${{ steps.set-outputs.outputs.registry }}
      version: ${{ steps.set-outputs.outputs.version }}
      http_proxy: ${{ steps.set-outputs.outputs.http_proxy }}
      https_proxy: ${{ steps.set-outputs.outputs.https_proxy }}
    steps:
      - name: set other outputs
        id: set-outputs
        run: |
          echo "image=$(echo '${{ env.REGISTRY }}/${{ env.REPO }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "registry=${{ env.REGISTRY }}" >> "$GITHUB_OUTPUT"
          echo "version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
          echo "http_proxy=${{ env.HTTP_PROXY }}" >> "$GITHUB_OUTPUT"
          echo "https_proxy=${{ env.HTTPS_PROXY }}" >> "$GITHUB_OUTPUT"

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - base: debian:12
            distro: debian
            codename: bookworm
            tag: "12"
          - base: debian:13
            distro: debian
            codename: trixie
            tag: "13"
          - base: debian:forky
            distro: debian
            codename: forky
            tag: "14"
          - base: fedora:41
            distro: fedora
            codename: ""
            tag: "41"
          - base: fedora:42
            distro: fedora
            codename: ""
            tag: "42"
          - base: fedora:43
            distro: fedora
            codename: ""
            tag: "43"
          - base: fedora:44
            distro: fedora
            codename: ""
            tag: "44"
          - base: ubuntu:20.04
            distro: ubuntu
            codename: focal
            tag: "20.04"
          - base: ubuntu:22.04
            distro: ubuntu
            codename: jammy
            tag: "22.04"
          - base: ubuntu:24.04
            distro: ubuntu
            codename: noble
            tag: "24.04"
          - base: ubuntu:26.04
            distro: ubuntu
            codename: resolute
            tag: "26.04"
    uses: docker/github-builder/.github/workflows/build.yml@58cb9f5b71b1836d6f690c1e95effdeb9b98cb8a # v1.17.0
    name: build - ${{ matrix.base }}
    needs:
      - build-prepare
    permissions:
      contents: read
      packages: write
    with:
      setup-qemu: false
      cache: false
      fail-fast: false
      context: .
      output: image
      build-args: |
        PARENT=${{ matrix.base }}
        HTTP_PROXY=${{ needs.build-prepare.outputs.http_proxy || '' }}
        HTTPS_PROXY=${{ needs.build-prepare.outputs.https_proxy || '' }}
      platforms: linux/amd64,linux/arm64
      push: true
      set-meta-labels: true
      meta-images: |
        ${{ needs.build-prepare.outputs.image }}
      meta-tags: |
        ${{ matrix.codename && format('{0}-{1}-v{2}', matrix.distro, matrix.codename, needs.build-prepare.outputs.version) }}
        ${{ matrix.codename && format('{0}-{1}-latest', matrix.distro, matrix.codename) }}
        ${{ matrix.tag && format('{0}-{1}-v{2}', matrix.distro, matrix.tag, needs.build-prepare.outputs.version) }}
        ${{ matrix.tag && format('{0}-{1}-latest', matrix.distro, matrix.tag) }}
      sign: false
    secrets:
      registry-auths: |
        - registry: ${{ needs.build-prepare.outputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
