name: Cleanup untagged GHCR images

on:
  schedule:
    - cron: "0 2 * * 6"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete untagged images older than 7 days
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
        with:
          delete-untagged: true
          older-than: 7 days
