name: Cleanup untagged GHCR images

on:
  schedule:
    - cron: "0 2 * * 6"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete untagged images
        uses: Chizkiyahu/delete-untagged-ghcr-action@707cf4f1445ec3e3f5c7bfc83a023fb868cd1174 # v6.1.1
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: ${{ github.event.repository.name }}
          untagged_only: true
          owner_type: user # or org
          except_untagged_multiplatform: true
