name: Generate Package Files

on:
  workflow_dispatch:
  schedule: 
    - cron: '55 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run generate-prereqs.sh
      run: sh scripts/generate-prerequisites.sh "https://raw.githubusercontent.com/Freetz-NG/freetz-ng/master/docs/PREREQUISITES.md" prerequisites
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "Update in upstream content"
        delete-branch: true
        title: 'PREREQUISITES.md (https://github.com/Freetz-NG/) were updated'

