name: Test Freetz-NG Build on Docker image

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Distro to build"
        required: true
        default: "_all"
        type: choice
        options:
          - "_all"
          - "fedora-43-latest" #fedora:43
          - "debian-13-latest" #debian:13
          - "ubuntu-22.04-latest" #ubuntu:22.04
          - "ubuntu-24.04-latest" #ubuntu:24.04
          - "ubuntu-26.04-latest" #ubuntu:26.04
      fos:
        description: "FOS Version to build"
        required: true
        default: "08_2X"
        type: choice
        options:
          - "04_XX"
          - "05_2X"
          - "05_5X"
          - "06_0X"
          - "06_2X"
          - "06_5X"
          - "06_8X"
          - "06_9X"
          - "07_0X"
          - "07_1X"
          - "07_2X"
          - "07_5X"
          - "08_0X"
          - "08_2X"
      box:
        description: "BOX Type to build"
        required: true
        default: "7530_W5"
        type: string
      tools:
        description: "Compile Tools?"
        required: true
        default: "yes"
        type: choice
        options:
          - "yes"
          - "no"
      rootemu:
        description: "Use Rootemu?"
        required: true
        default: "pseudo"
        type: choice
        options:
          - "fakeroot"
          - "pseudo"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  dockerfizieren:
    runs-on: ubuntu-slim

    outputs:
      os: ${{ steps.parse.outputs.os }}
    
    steps:
      - name: list
        id: list
        run: |
          if [ "${{ github.event.inputs.os }}" != "_all" ]; then \
            OSLIST="
            ${{ github.event.inputs.os }}
            "
          else
            OSLIST="
            fedora-43-latest
            debian-13-latest
            ubuntu-22.04-latest
            ubuntu-24.04-latest
            ubuntu-26.04-latest
            "
          fi
          echo "oslist<<EOF" >> $GITHUB_OUTPUT
          echo "$OSLIST" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: parse
        id: parse
        run: |
          OSLIST="${{ steps.list.outputs.oslist }}"
          OSLIST_JSON=$(echo "$OSLIST" | awk 'NF {printf "\"%s\",", $0}' | sed 's/,$//')
          echo "os=[$OSLIST_JSON]" >> $GITHUB_OUTPUT
          echo "################################################################"
          echo "OSLIST_JSON=[$OSLIST_JSON]"

  build:
    permissions:
      contents: read
    container:
      image: ghcr.io/pfichtner/pfichtner-freetz:${{ matrix.docker }}
      options: --user 1001:1001
    needs: [ dockerfizieren ]
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        docker: ${{ fromJson(needs.dockerfizieren.outputs.os) }}
        runner: [ arm64, amd64 ]
    name: "${{ matrix.runner == 'arm64' && 'ARM64' || 'AMD64' }}--${{ matrix.docker }}"
    runs-on: ubuntu-24.04${{ matrix.runner == 'arm64' && '-arm' || '' }}

    steps:

      - name: sleep
        run: |
          SLEEP="$((1 + $(od -A n -t d -N 2 /dev/urandom | tr -d ' ') % 9))"
          echo "Sleeping $SLEEP seconds ..."
          sleep $SLEEP

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF_NAME: master
          REPOSITORY: Freetz-NG/freetz-ng
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github-actions:$GITHUB_TOKEN@${GITHUB_SERVER_URL##*/}/$REPOSITORY.git $GITHUB_WORKSPACE
          git checkout $REF_NAME

      - name: config
        run: |
          FOS="${{ github.event.inputs.fos }}"
          BOX="${{ github.event.inputs.box }}"
          truncate -s0 .config
          echo 'FREETZ_MODULES_OWN=""'                                                                >> .config
          for x in  UDEVMOUNT                               ; do echo "# FREETZ_PATCH_$x is not set"  >> .config; done
          for x in  dummy loop usbserial                   ; do echo "# FREETZ_MODULE_$x is not set"  >> .config; done
          for x in  DROPBEAR                              ; do echo "# FREETZ_PACKAGE_$x is not set"  >> .config; done
          for x in  LDD                                              ; do echo "FREETZ_PACKAGE_$x=y"  >> .config; done
          for x in  COMPRESSED  UNCOMPRESSED                        ; do echo "FREETZ_SIZEINFO_$x=y"  >> .config; done
          echo '# FREETZ_TOOLCHAIN_CCACHE is not set'                                                 >> .config
          echo 'FREETZ_VERBOSITY_FWMOD_2=y'                                                           >> .config
          echo 'FREETZ_VERBOSITY_LEVEL_0=y'                                                           >> .config
          echo 'FREETZ_VERBOSITY_LEVEL=0'                                                             >> .config
          echo 'FREETZ_SERIES_ALL=y'                                                                  >> .config
          echo 'FREETZ_USER_LEVEL_DEVELOPER=y'                                                        >> .config
          echo '# FREETZ_MODULES_TEST in not set'                                                     >> .config
          echo 'FREETZ_DL_SITE_USER="https://github.com/Freetz-NG/dl-mirror/releases/download/dl"'    >> .config
          grep -q '^FREETZ_TYPE_' .config || echo "FREETZ_TYPE_$BOX=y"                                >> .config
          grep -q '^FREETZ_TYPE_FIRMWARE_' .config || echo "FREETZ_TYPE_FIRMWARE_$FOS=y"              >> .config
          echo "################################################################" && du .config && wc -l .config

      - name: extra_config
        shell: bash
        run: |
          COMPILE_TOOLS="${{ github.event.inputs.tools }}"
          USE_ROOTEMU="${{ github.event.inputs.rootemu }}"
          [[ "$COMPILE_TOOLS" == "yes" ]] && echo '# FREETZ_DOWNLOAD_TOOLCHAIN is not set'            >> .config
          [[ "$COMPILE_TOOLS" != "yes" ]] && echo 'FREETZ_DOWNLOAD_TOOLCHAIN=y'                       >> .config
          [[ "$COMPILE_TOOLS" == "yes" ]] && echo '# FREETZ_HOSTTOOLS_DOWNLOAD is not set'            >> .config
          [[ "$COMPILE_TOOLS" != "yes" ]] && echo 'FREETZ_HOSTTOOLS_DOWNLOAD=y'                       >> .config
          [[ "$USE_ROOTEMU" == "pseudo"   ]] && echo '# FREETZ_ROOTEMU_FAKEROOT is not set'           >> .config
          [[ "$USE_ROOTEMU" != "pseudo"   ]] && echo 'FREETZ_ROOTEMU_FAKEROOT=y'                      >> .config
          [[ "$USE_ROOTEMU" == "fakeroot" ]] && echo '# FREETZ_ROOTEMU_PSEUDO is not set'             >> .config
          [[ "$USE_ROOTEMU" != "fakeroot" ]] && echo 'FREETZ_ROOTEMU_PSEUDO=y'                        >> .config
          echo "################################################################" && du .config && wc -l .config

      - name: generate
        run: |
          make && rm -f images/latest.image
          
      - name: result
        run: |
          echo "################################################################"
          ls -l images/
          sha256sum images/*

      - name: vars
        id: vars
        run: |
          LINK="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          LAST="$(ls images/*.image | sed 's,.*/,,;s,\.image$,,')"
          NAME="$(ls images/*.image | sed 's,.*/,,;s,_[0-9].*,,')"
          [ -n "$LINK" ] && echo "link=$LINK" >> $GITHUB_OUTPUT
          [ -n "$LAST" ] && echo "last=$LAST" >> $GITHUB_OUTPUT
          [ -n "$NAME" ] && echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "################################################################"
          echo "LINK=$LINK"
          echo "LAST=$LAST"
          echo "NAME=$NAME"
          test -n "$NAME"
