name: Freetz Build

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        default: "_all"
      fos:
        required: true
        default: "08_2X"
      box:
        required: true
        default: "7530_W5"
      tools:
        required: true
        default: "yes"
      rootemu:
        required: true
        default: "pseudo"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-slim
    outputs:
      os: ${{ steps.matrix.outputs.os }}
    steps:
      - uses: actions/checkout@v6

      - id: matrix
        run: |
          OUTPUT=$( .github/scripts/ci.sh prepare-matrix "${{ inputs.os }}" )
          echo "$OUTPUT" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        docker: ${{ fromJson(needs.matrix.outputs.os) }}
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]
    runs-on: '${{ matrix.runner }}'
    container:
      image: ghcr.io/pfichtner/pfichtner-freetz:${{ matrix.docker }}
      options: --user 1001:1001
    env:
      FREETZ_CLONE_PATH: '${{ github.workspace }}/freetz'
      FREETZ_REPO: Freetz-NG/freetz-ng
      MAIN_CLONE_PATH: '${{ github.workspace }}' 
      MAIN_REPO: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ env.MAIN_REPO }}
          path: ${{ env.MAIN_CLONE_PATH }}
      - name: Checkout Freetz-NG
        uses: actions/checkout@v6
        with:
          repository: ${{ env.FREETZ_REPO }}
          path: ${{ env.FREETZ_CLONE_PATH }}

      - name: Config
        working-directory: ${{ env.FREETZ_CLONE_PATH }}
        run: |
          ../.github/scripts/ci.sh config \
            "${{ inputs.fos }}" \
            "${{ inputs.box }}"

      - name: Extra config
        working-directory: ${{ env.FREETZ_CLONE_PATH }} 
        run: |
          ../.github/scripts/ci.sh extra-config \
            "${{ inputs.tools }}" \
            "${{ inputs.rootemu }}"

      - name: Build
        working-directory: ${{ env.FREETZ_CLONE_PATH }}
        run: ../.github/scripts/ci.sh build

      - name: Result
        working-directory: ${{ env.FREETZ_CLONE_PATH }}
        run: ../.github/scripts/ci.sh result

      - name: Vars
        working-directory: ${{ env.FREETZ_CLONE_PATH }}
        id: vars
        run: |
          OUTPUT=$( ../.github/scripts/ci.sh vars )
          echo "$OUTPUT" >> $GITHUB_OUTPUT
